name: sep_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
    
  # This dependency is breaking builds after adding a Widget Extension in Xcode
  google_mlkit_barcode_scanning: ^0.12.1

  # These are dependencies from the production app integrating home_widget that don't
  # appear to be the cause of any issues, but are here to better approximate the app.
  avatar_stack: ^1.2.0
  camerawesome: ^2.1.0
  chart_sparkline: ^1.1.1
  collection: ^1.18.0
  context_watch: ^5.0.1
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.2.2
  easy_debounce: ^2.0.3
  file_picker: ^8.1.2
  flame_audio: ^2.10.3
  flutter_confetti: ^0.3.0
  google_fonts: ^6.2.1
  # google_mlkit_barcode_scanning: ^0.12.0
  health: ^11.0.0
  http: ^1.2.2
  image: ^4.2.0
  in_app_review: ^2.0.9
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  nanoid2: ^2.0.1
  page_indicator_plus: ^1.0.4
  page_transition: ^2.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  permission_handler: ^11.3.1
  phosphor_flutter: ^2.1.0
  pull_down_button: ^0.10.1
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sprung: ^3.0.1
  typeset: ^2.1.2
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3

flutter:
  uses-material-design: true
